language: node_js
node_js:
  - node
jobs:
  fast finish: true
env:
  - PREFIX=!
  - COLOR=#3499DC
  - NODE_ENV=dev # redundant

before_install:
  - npm install -g npm # get latest npm version
before_script:
  - npm run build
# default test ok